### ISSUE TITLE
Allow spawning task from outside an Executor

### ISSUE THREAD

**Issue by Keruspe** [stjepang/async-executor#1]
With smol 0.2 and below, we could spawn tasks from anywhere, starting with smol 0.3 which uses async-executor, it's no longer possible. It makes it impossible to spawn tasks from e.g. a custom reactor thread which doesn't run on the Executor.
This seem to be a pretty sad regression.

It would be great to at least have some king of handle to spawn tasks on the executor from the outside?

**Comment by stjepang** [comment]
I personally found sharing a single executor among all calls of `smol::run()` not great.

The reason is that more often than not I want separate "execution contexts" with `smol::run()` that don't mix up each other's tasks. In particular, if a panic occurs in a task by one `smol::run()`, I don't want another `smol::run()` to pick it up and panic instead. This get especially annoying in unit tests.

However, you can have the old behavior by declaring a global executor:

```rust
lazy_static! {
    static ref GLOBAL: Executor = {
        let ex = Executor::new();
        // spawn threads...
        ex
    };
}
```

and then spawning tasks with `GLOBAL.spawn(future)`. How does that look?

**Comment by stjepang** [comment]
Also, note that smol itself is now a trivial amount of code so it's easier than ever to fork :)

**Comment by Keruspe** [comment]
I totally agree with all of that.
In my case, I'm not writing the final application, I'm integrating smol as an option in a library. With async-std and smol <0.3, I just spawned a task. With tokio, I register a handle from within the executor, and spawn tasks using this handle. With smol 0.3 I can do neither.

Would you be open to this kind of handle to spawn a task on an executor from outside of it?

**Comment by stjepang** [comment]
I guess that handle would be something like `Spawner` and `LocalSpawner` types from `futures`?
https://docs.rs/futures/0.3.5/futures/executor/struct.LocalPool.html#method.spawner

If so, then yeah, I would be open to adding that!

**Comment by Keruspe** [comment]
Something like this yep, do you want me to give it a shot?

**Comment by Keruspe** [comment]
FWIW, just retried my failing test using the new spawner, eveything now works as expected!
